In [41]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [42]:
data = pd.read_csv('data/train.csv')

In [43]:
df = np.array(data)

In [44]:
m , n = df.shape

In [45]:
np.random.shuffle(df)

In [46]:
print(df)

[[8 0 0 ... 0 0 0]
 [6 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 ...
 [6 0 0 ... 0 0 0]
 [3 0 0 ... 0 0 0]
 [2 0 0 ... 0 0 0]]


In [47]:
data_dev = df[:1000].T
y_dev = data_dev[0]
X_dev = data_dev[1:n]
X_dev = X_dev/255

In [48]:
data_train = df[1000:m].T
y_train = data_train[0]
X_train = data_train[1:n]
X_train = X_train/255
_,m_train = X_train.shape

In [49]:
class NeuralNetwork:
    def __init__(self):
        self.W1 = np.random.rand(10, 784) - 0.5
        self.b1 = np.random.rand(10, 1) - 0.5
        self.W2 = np.random.rand(10, 10) - 0.5
        self.b2 = np.random.rand(10, 1) - 0.5

    def ReLU(self, Z):
        return np.maximum(0, Z)

    def softmax(self, Z):
        exp_Z = np.exp(Z - np.max(Z, axis=0, keepdims=True)) 
        return exp_Z / np.sum(exp_Z, axis=0, keepdims=True)

    def forward(self, X):
        Z1 = self.W1.dot(X) + self.b1
        A1 = self.ReLU(Z1)
        Z2 = self.W2.dot(A1) + self.b2
        A2 = self.softmax(Z2)
        return Z1, A1, Z2, A2

    def one_hot(self, Y):
        one_hot_Y = np.zeros((Y.max() + 1, Y.size))
        one_hot_Y[Y, np.arange(Y.size)] = 1
        return one_hot_Y

    def deriv_relu(self, Z):
        return Z > 0

    def backpro(self, Z1, A1, Z2, A2, Y, X):
        m = Y.size
        one_hot_Y = self.one_hot(Y)
        dZ2 = A2 - one_hot_Y
        dW2 = (1 / m) * dZ2.dot(A1.T)
        db2 = (1 / m) * np.sum(dZ2, axis=1, keepdims=True)
        
        dZ1 = self.W2.T.dot(dZ2) * self.deriv_relu(Z1)
        dW1 = (1 / m) * dZ1.dot(X.T)
        db1 = (1 / m) * np.sum(dZ1, axis=1, keepdims=True)

        return dW1, db1, dW2, db2

    def update_params(self, dW1, db1, dW2, db2, alpha):
        self.W1 = self.W1 - alpha * dW1
        self.b1 = self.b1 - alpha * db1
        self.W2 = self.W2 - alpha * dW2
        self.b2 = self.b2 - alpha * db2

In [52]:
def get_prediction(A2):
    return np.argmax(A2,0)

def get_accuration(prediction,Y):
    print("prediction:", prediction, "actual:", Y)
    return np.sum(prediction ==Y)/ Y.size

def gradient_descend(X,Y,iterations, alpha):
    model = NeuralNetwork()
    for i in range(iterations):
        Z1,A1,Z2,A2 = model.forward(X)
        dW1,db1,dW2,db2 = model.backpro(Z1,A1,Z2,A2,Y,X)
        model.update_params(dW1,db1,dW2,db2,alpha)
        if i%50 ==0:
            print("iteration:", i)
            print("accuration:", get_accuration(get_prediction(A2),Y))
    

    return model.W1,model.b1,model.W2,model.b2



In [53]:
W1,b1,W2,b2 = gradient_descend(X_train,y_train,500,0.1)

iteration: 0
prediction: [7 7 7 ... 7 7 0] actual: [1 8 7 ... 6 3 2]
accuration: 0.09921951219512196
iteration: 50
prediction: [3 4 6 ... 6 1 0] actual: [1 8 7 ... 6 3 2]
accuration: 0.35821951219512194
iteration: 100
prediction: [1 8 7 ... 6 3 0] actual: [1 8 7 ... 6 3 2]
accuration: 0.5765365853658536
iteration: 150
prediction: [1 8 7 ... 6 3 0] actual: [1 8 7 ... 6 3 2]
accuration: 0.6742682926829269
iteration: 200
prediction: [1 8 7 ... 6 3 0] actual: [1 8 7 ... 6 3 2]
accuration: 0.7190243902439024
iteration: 250
prediction: [1 8 7 ... 6 3 0] actual: [1 8 7 ... 6 3 2]
accuration: 0.7447317073170732
iteration: 300
prediction: [1 8 7 ... 6 3 0] actual: [1 8 7 ... 6 3 2]
accuration: 0.7660487804878049
iteration: 350
prediction: [1 8 7 ... 6 3 0] actual: [1 8 7 ... 6 3 2]
accuration: 0.7814390243902439
iteration: 400
prediction: [1 8 7 ... 6 3 0] actual: [1 8 7 ... 6 3 2]
accuration: 0.7937560975609756
iteration: 450
prediction: [1 8 7 ... 6 3 0] actual: [1 8 7 ... 6 3 2]
accuration: 